.Dd April 19, 2020
.Dt RDD 1
.Os
.Sh NAME
.Nm rdd
.Nd random data dump
.Sh SYNOPSIS
.Nm
.Op Fl i Ar source
.Op Fl r Ar rekeymb
.Op Fl v
.Sh DESCRIPTION
.Nm
is a high-speed, cryptographically safe random data generator
using optimized versions of the ChaCha8 stream cipher,
depending on your CPU.
It is designed to fill crypto devices with random data.
.Pp
Random binary data is written to standard output.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl i Ar source
Read key and IVs from
.Ar source
(default:
.Pa /dev/urandom )
.It Fl r Ar rekeymb
Reload the IV every
.Ar rekeymb
megabytes of output (default: 4).
.It Fl v
Print a
.Sq Li \&.
to standard error on every rekey.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr dd 1 ,
.Xr random 4 ,
.Xr random 7
.Sh NOTES
rdd reads 40 random bytes for the initial key and 32 bytes for every rekeying
from the random source.
Setting
.Ar rekeymb
to -1 never rekeys.
.Pp
This implementation passed dieharder 3.31.1 "-a" and
PractRand/RNG_test 0.95 (tested up to 32 TB).
.Sh AUTHORS
.An Leah Neukirchen Aq Mt leah@vuxu.org
.Sh LICENSE
.Nm
is in the public domain.
.Pp
To the extent possible under law,
the creator of this work
has waived all copyright and related or
neighboring rights to this work.
.Pp
.Lk http://creativecommons.org/publicdomain/zero/1.0/
.Pp
This program uses the public domain library chacha-opt.
